### ISSUE TITLE
blog link is dead

### ISSUE THREAD

**Issue by Colerar** [square/git-fastclone#62]
https://corner.squareup.com/2015/11/fastclone.html is redirecting to https://developer.squareup.com/blog/, is there a new link?

**Comment by mtauraso** [comment]
Try this: https://developer.squareup.com/blog/introducing-git-fastclone/

Found by searching for 'fastclone' on https://developer.squareup.com/blog/

**Comment by justinseanmartin** [comment]
Thanks for the report, I just merged a change to the README to fix the link.
