### ISSUE TITLE
[Windows] Submodule filename contains characters that can't be used in windows

### ISSUE THREAD

**Issue by DEMON1A** [square/git-fastclone#64]
I came across this function in git-fastclone that writes a submodule file for the current repo being downloaded

```ruby
def reference_repo_submodule_file(url, reference_dir, using_local_repo)
      "#{reference_repo_dir(url, reference_dir, using_local_repo)}:submodules.txt"
end
```
> The code is located inside lib/git-fastclone.rb within these lines **50-52**

The submodule file is never created though in windows, because `:` character isn't allowed in windows filenames, Maybe you should change this? I don't see a problem changing that character since the only usage of it is here, and it's just for creating the file that's totally controlled by your ruby code

```ruby
def update_submodule_reference(url, submodule_url_list)
      return if submodule_url_list.empty? || prefetch_submodules.nil?

      with_reference_repo_lock(url) do
        # Write the dependency file using submodule list
        File.open(reference_repo_submodule_file(url, reference_dir, using_local_repo), 'w') do |f|
          submodule_url_list.each { |submodule_url| f.write("#{submodule_url}\n") }
        end
      end
end
```
> The code is located inside lib/git-fastclone.rb within these lines **302-311**

**Comment by DEMON1A** [comment]
The hardcoding of `/var/tmp/git-fastclone` isn't really a problem on windows I did test it out before creating the issue and the way it works is just by creating the folder base like this `{DISK}:/var/tmp/git-fastclone` for example if you're running git-fastclone on your `E;\` disk you're getting a folder named `E:\\var\\tmp\\git-fastclone` created and everything would be working fine until the `:` column part of the file creating, I did a full analysis on windows

Ruby itself supports both Windows and Linux, git-fastclone was built for Linux clearly but it can/should be supported for windows, I seen most of the functionality during my analysis is running normally just the installation part that fails, However a simple platform checks using `RbConfig::CONFIG['host_os']` in ruby like this we would be able to make git-fastclone run on both systems and it wouldn't really affect anyone using linux, the column functionality would be still working for old repos that got downloaded

I can make the changes and submit a PR as you recommended if you're okay with what I just explained

**Comment by justinseanmartin** [comment]
Yep, using `host_os` to alter the delimiter on lines 51 and 56 from `:` to something else that is generally easy to differentiate from the repo name portion (maybe using a double hyphen or double underscore?) seems reasonable to me.

**Comment by DEMON1A** [comment]
Hey @justinseanmartin, I created a PR #65 that adds windows support for git-fastclone, I just tested it and everything seems cool one function managed to solve the issue

```css
E:\Projects\Ruby\git-fastclone>ruby -Ilib bin\git-fastclone https://github.com/DEMON1A/WEngine
git-fastclone 1.4.4
Cloning WEngine to E:/Projects/Ruby/git-fastclone/WEngine
Checkout of WEngine took 3.3245968s
```

**Comment by DEMON1A** [comment]
Closing this issue since the PR has been merged already
